#!/bin/sh

update()
{
  sudo apt update
}

upgrade()
{
  sudo apt upgrade -y
}

autoclean()
{
  sudo apt autoclean -y
}

dist-upgrade()
{
  sudo apt dist-upgrade -y
}

release-upgrade()
{
  sudo do-release-upgrade
}

update && upgrade && dist-upgrade &&  autoclean && release-upgrade
