#!/bin/sh

update()
{
  sudo apt update
}

upgrade()
{
  sudo apt upgrade -y
}

autoclean()
{
  sudo apt autoclean -y
}

dist_upgrade()
{
  sudo apt dist-upgrade -y
}

do_release_upgrade()
{
  sudo do-release-upgrade
}

update && upgrade && dist_upgrade &&  autoclean && do_release_upgrade
