#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

. "$DIR/lib/update.lib.sh"

update
upgrade
dist_upgrade
autoclean
autoremove

case $1 in
    "--release" | "-r")
        do_release_upgrade;;
esac
